import "server-only";

import { clientEnv } from "@/lib/env.client";
import { env } from "@/lib/env.server";
import { logger } from "@/lib/logger";

import { OAuthNotConfiguredError, OAuthRequestFailedError, postOAuthForm } from "../../shared/oauth-http";
import { GOOGLE_OAUTH_SCOPES } from "./types";
import type { GoogleTokenResponse, GoogleUserInfoResponse } from "./types";

const PROVIDER = "Google";

const AUTHORIZATION_ENDPOINT = "https://accounts.google.com/o/oauth2/v2/auth";
const TOKEN_ENDPOINT = "https://oauth2.googleapis.com/token";
const USERINFO_ENDPOINT = "https://openidconnect.googleapis.com/v1/userinfo";
const REVOKE_ENDPOINT = "https://oauth2.googleapis.com/revoke";

export function isGoogleOAuthConfigured(): boolean {
  return Boolean(env.GOOGLE_CLIENT_ID && env.GOOGLE_CLIENT_SECRET);
}

function requireCredentials(): { clientId: string; clientSecret: string } {
  if (!env.GOOGLE_CLIENT_ID || !env.GOOGLE_CLIENT_SECRET) {
    throw new OAuthNotConfiguredError(PROVIDER);
  }
  return { clientId: env.GOOGLE_CLIENT_ID, clientSecret: env.GOOGLE_CLIENT_SECRET };
}

export function getRedirectUri(): string {
  return `${clientEnv.NEXT_PUBLIC_APP_URL}/api/connectors/google/callback`;
}

/** Builds the real Google consent-screen URL — no mocked/local
 * authorization flow. PKCE (`code_challenge`) comes from the shared
 * `shared/pkce.ts`, generated by the caller (the authorize route). */
export function buildAuthorizationUrl(input: { state: string; codeChallenge: string }): string {
  const { clientId } = requireCredentials();

  const url = new URL(AUTHORIZATION_ENDPOINT);
  url.searchParams.set("client_id", clientId);
  url.searchParams.set("redirect_uri", getRedirectUri());
  url.searchParams.set("response_type", "code");
  url.searchParams.set("scope", GOOGLE_OAUTH_SCOPES.map((s) => s.scope).join(" "));
  url.searchParams.set("access_type", "offline");
  url.searchParams.set("prompt", "consent");
  url.searchParams.set("state", input.state);
  url.searchParams.set("code_challenge", input.codeChallenge);
  url.searchParams.set("code_challenge_method", "S256");

  return url.toString();
}

/** Real authorization-code exchange — https://developers.google.com/identity/protocols/oauth2/web-server#exchange-authorization-code */
export async function exchangeCodeForTokens(code: string, codeVerifier: string): Promise<GoogleTokenResponse> {
  const { clientId, clientSecret } = requireCredentials();

  return postOAuthForm<GoogleTokenResponse>(PROVIDER, TOKEN_ENDPOINT, {
    code,
    client_id: clientId,
    client_secret: clientSecret,
    redirect_uri: getRedirectUri(),
    grant_type: "authorization_code",
    code_verifier: codeVerifier,
  });
}

/** Real refresh-token exchange. Google does not return a new
 * `refresh_token` on refresh — callers must keep the original. */
export async function refreshAccessToken(refreshToken: string): Promise<GoogleTokenResponse> {
  const { clientId, clientSecret } = requireCredentials();

  return postOAuthForm<GoogleTokenResponse>(PROVIDER, TOKEN_ENDPOINT, {
    refresh_token: refreshToken,
    client_id: clientId,
    client_secret: clientSecret,
    grant_type: "refresh_token",
  });
}

/** Real userinfo fetch — https://developers.google.com/identity/openid-connect/openid-connect#obtaininguserprofileinformation */
export async function fetchGoogleUserInfo(accessToken: string): Promise<GoogleUserInfoResponse> {
  const response = await fetch(USERINFO_ENDPOINT, {
    headers: { Authorization: `Bearer ${accessToken}` },
  });

  if (!response.ok) {
    throw new OAuthRequestFailedError(PROVIDER, `Google userinfo request failed (${response.status}).`);
  }

  return response.json() as Promise<GoogleUserInfoResponse>;
}

/** Real token revocation — https://developers.google.com/identity/protocols/oauth2/web-server#tokenrevoke.
 * Best-effort: a revoke failure shouldn't block the user from
 * disconnecting locally, so callers should log, not throw, on failure. */
export async function revokeToken(token: string): Promise<void> {
  const response = await fetch(REVOKE_ENDPOINT, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({ token }).toString(),
  });

  if (!response.ok) {
    const detail = await response.text().catch(() => "");
    logger.error("google_connector.revoke_failed", { status: response.status, detail });
  }
}
